import {UserDetailsProps} from './types';

export const users: UserDetailsProps[] = [
  {
    _id: '1',
    username: 'johndoe1',
    email: 'johndoe1@example.com',
    dob: '1990-05-15',
    hobbies: ['reading', 'hiking'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/1.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/2.jpg',
      'https://randomuser.me/api/portraits/men/3.jpg',
    ],
    phone: '555-1234',
    gender: 'male',
    password: 'password123',
    location: 'Edo',
    age: '25',
  },
  {
    _id: '2',
    username: 'janedoe2',
    email: 'janedoe2@example.com',
    dob: '1985-10-20',
    hobbies: ['cooking', 'painting'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/1.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/2.jpg',
      'https://randomuser.me/api/portraits/women/3.jpg',
    ],
    phone: '555-5678',
    gender: 'female',
    password: 'securepassword',
    location: 'Edo',
    age: '29',
  },
  {
    _id: '3',
    username: 'mikesmith3',
    email: 'mikesmith3@example.com',
    dob: '1978-03-22',
    hobbies: ['cycling', 'photography'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/3.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/4.jpg',
      'https://randomuser.me/api/portraits/men/5.jpg',
    ],
    phone: '555-8765',
    gender: 'male',
    password: 'mikepass78',
    location: 'Ikeja, Lagos',
    age: '17',
  },
  {
    _id: '4',
    username: 'emilyjones4',
    email: 'emilyjones4@example.com',
    dob: '1992-07-11',
    hobbies: ['yoga', 'traveling'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/4.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/5.jpg',
      'https://randomuser.me/api/portraits/women/6.jpg',
    ],
    phone: '555-4321',
    gender: 'female',
    password: 'emily1992',
    location: 'Ikorodu, Lagos',
    age: '18',
  },
  {
    _id: '5',
    username: 'davidharris5',
    email: 'davidharris5@example.com',
    dob: '1983-11-30',
    hobbies: ['gaming', 'gardening'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/5.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/6.jpg',
      'https://randomuser.me/api/portraits/men/7.jpg',
    ],
    phone: '555-6789',
    gender: 'male',
    password: 'david83pass',
    location: 'Ikoyi, Lagos',
    age: '32',
  },
  {
    _id: '6',
    username: 'sarahwilson6',
    email: 'sarahwilson6@example.com',
    dob: '1995-02-14',
    hobbies: ['dancing', 'writing'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/6.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/7.jpg',
      'https://randomuser.me/api/portraits/women/8.jpg',
    ],
    phone: '555-9876',
    gender: 'female',
    password: 'sarah95',
    location: 'Ikeja, Lagos',
    age: '33',
  },
  {
    _id: '7',
    username: 'chrisbrown7',
    email: 'chrisbrown7@example.com',
    dob: '1988-09-09',
    hobbies: ['running', 'swimming'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/7.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/8.jpg',
      'https://randomuser.me/api/portraits/men/9.jpg',
    ],
    phone: '555-3456',
    gender: 'male',
    password: 'chris88',
    location: 'Ikotun, Lagos',
    age: '18',
  },
  {
    _id: '8',
    username: 'lauradavis8',
    email: 'lauradavis8@example.com',
    dob: '1991-12-25',
    hobbies: ['singing', 'baking'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/8.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/9.jpg',
      'https://randomuser.me/api/portraits/women/10.jpg',
    ],
    phone: '555-6543',
    gender: 'female',
    password: 'laura1991',
    location: 'VI, Lagos',
    age: '28',
  },
  {
    _id: '9',
    username: 'matthewmiller9',
    email: 'matthewmiller9@example.com',
    dob: '1980-04-18',
    hobbies: ['fishing', 'woodworking'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/9.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/10.jpg',
      'https://randomuser.me/api/portraits/men/11.jpg',
    ],
    phone: '555-7890',
    gender: 'male',
    password: 'matt80',
    location: 'Ikeja, Lagos',
    age: '20',
  },
  {
    _id: '10',
    username: 'oliviaroberts10',
    email: 'oliviaroberts10@example.com',
    dob: '1993-08-05',
    hobbies: ['painting', 'skiing'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/10.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/11.jpg',
      'https://randomuser.me/api/portraits/women/12.jpg',
    ],
    phone: '555-3210',
    gender: 'female',
    password: 'olivia93',
    location: 'Ikeja, Lagos',
    age: '40',
  },
  {
    _id: '11',
    username: 'alexjohnson11',
    email: 'alexjohnson11@example.com',
    dob: '1987-01-23',
    hobbies: ['photography', 'traveling'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/11.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/12.jpg',
      'https://randomuser.me/api/portraits/men/13.jpg',
    ],
    phone: '555-2345',
    gender: 'male',
    password: 'alex1987',
    location: 'Lagos',
    age: '42',
  },
  {
    _id: '12',
    username: 'bethanysmith12',
    email: 'bethanysmith12@example.com',
    dob: '1994-06-17',
    hobbies: ['cooking', 'reading'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/12.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/13.jpg',
      'https://randomuser.me/api/portraits/women/14.jpg',
    ],
    phone: '555-6789',
    gender: 'female',
    password: 'bethany1994',
    location: 'Lagos',
    age: '19',
  },
  {
    _id: '13',
    username: 'charlesdavis13',
    email: 'charlesdavis13@example.com',
    dob: '1982-11-05',
    hobbies: ['hiking', 'gaming'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/13.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/14.jpg',
      'https://randomuser.me/api/portraits/men/15.jpg',
    ],
    phone: '555-3456',
    gender: 'male',
    password: 'charles1982',
    location: 'Lagos',
    age: '36',
  },
  {
    _id: '14',
    username: 'daniellewilliams14',
    email: 'daniellewilliams14@example.com',
    dob: '1990-09-12',
    hobbies: ['yoga', 'painting'],
    profilePhoto: 'https://randomuser.me/api/portraits/women/14.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/women/15.jpg',
      'https://randomuser.me/api/portraits/women/16.jpg',
    ],
    phone: '555-7890',
    gender: 'female',
    password: 'danielle1990',
    location: 'Edo',
    age: '25',
  },
  {
    _id: '15',
    username: 'ethanmartinez15',
    email: 'ethanmartinez15@example.com',
    dob: '1985-03-30',
    hobbies: ['cycling', 'music'],
    profilePhoto: 'https://randomuser.me/api/portraits/men/15.jpg',
    otherPhotos: [
      'https://randomuser.me/api/portraits/men/16.jpg',
      'https://randomuser.me/api/portraits/men/17.jpg',
    ],
    phone: '555-0123',
    gender: 'male',
    password: 'ethan1985',
    location: 'Edo',
    age: '25',
  },
];
